### ISSUE TITLE
Honor CSS in HTML imports

### ISSUE THREAD

**Issue by Pilatch** [jhildenbiddle/get-css-data#1]
It would be convenient for this library to support `link[rel=import]` as a possible `include` setting. For example polyfilling (or ponyfilling) CSS custom properties would become significantly easier for utilities that depend on this one. That would allow broader support of web components that expect to use CSS variables, as the common method for using web components is via HTML imports.

That means this library would look at HTML imports, and apply the other rules present in the `include` setting to get their css data.

For instance, if we have an HTML file that is imported, "import1.html" and that HTML file has a style tag in its content, then get-css-data would return the CSS styles found in that style tag, assuming that the `include` setting has the selector `style` in it. There would be a similar outcome with another imported HTML file, "import2.html" that has a link to a stylesheet in it, should the `include` setting have the selector `link[rel="stylesheet"]`.

I've already started looking into the code to see how this could be supported.

One concern is recursive crawling of HTML imports. I haven't gotten that far yet!

**Comment by Pilatch** [comment]
Note this would probably also need to consider crawling for styles inside of `<template>` elements.

**Comment by jhildenbiddle** [comment]
Hi @Pilatch .

I haven't had an opportunity to work with HTML imports or templates, so forgive me if I'm skipping over a common use case when I say that adding support for these features doesn't seem like a good investment.

### HTML Imports

Per the warning in Chrome's console (v66):

```
[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M67, around May 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
```

More information is available [here](https://github.com/TakayoshiKochi/deprecate-style-in-html-imports). 

If I understand the change correctly, the recommendation moving forward is to remove `<style>` and `<link rel="stylesheet">` elements from HTML imports. The linked page provides hacks to get existing implementations to work after Chrome has removed support, but these hacks simply hoist the styles to the master document which `get-css-data` can then process as usual (no changes necessary).

It's also worth considering that HTML imports [haven't been widely adopted](https://caniuse.com/#search=html) despite being available in Chrome since 2013.

* Edge lists the feature as [Under Consideration](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/htmlimports/) but with a low priority.
* Firefox lists the feature as [Not Planned](https://platform-status.mozilla.org/#html-imports)
* Webkit lists the feature as [Not Considering](https://webkit.org/status/#feature-html-imports)

Why does this matter? Because the [polyfill](https://github.com/webcomponents/html-imports) used to provide HTML import support for these browsers inserts the import content directly into the master document, meaning `get-css-data` can process polyfilled import `<style>` and `<link>` elements as usual (no changes necessary).

```html
<!-- Before polyfill -->

<link rel="import" href="my-element.html">

<!-- After polyfill -->

<link rel="import" href="my-element.html">
  <!-- content of my-element.html -->
  <style>
    p {
      color: red;
    }
  </style>
  <p>Hello!</p>
</link>
```

### HTML Templates

HTML templates aren't rendered until they are manually cloned and added to the DOM via JavaScript, so there is little reason to parse them for `<style>` and `<link rel="stylehseet">` nodes beforehand. Once a template has been cloned and added to the DOM, `get-css-data` will be able to process any `<style>` or `<link>` elements they contain.

Whew. 😄 

If I've missed something please let me know. As I mentioned earlier, I'm not an expert on HTML imports or templates.

Thanks!

**Comment by Pilatch** [comment]
These are all good reasons to close the issue. I'll do that now.

Your reasoning is making me reconsider our web components technology approach. Maybe not wholesale, but I have to get these component definitions into the main page somehow!
